### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Englund0110** [tompet815/contract_viking_requirementbased#3]
_This is the review so far:_ 

Fine logical model with primary and foreign keys.

State diagram is also fine. 

Class diagram:

- In Booking, pickupTime appears two times.
- In RentalCars, enum can't contain '#'
- Missing constraints/invarients on methods. Why not parse objects as parameters?
- Why do you want to use both a Date and a Time object? (They both contains the same value like date and time)

Sequence diagram

- Why should "deliverCity" be a parameter for getting a list of available cars? 

Relationel Model

- Booking missing FK to rentalCar? How do i know which car has been booked?

**Comment by tompet815** [comment]
Class diagrams and Sequence diagram has been corrected.
Date and Time could be just Date object, as you point out. But I haven't changed diagram for consistency's matter (we have already stated Date and Time everywhere). 
You can pass object instead of tons of parameters. :)
